# Copyright (c) 2025 Giulio Cocconi
# SPDX-License-Identifier: MIT

{ lib, options, config, pkgs, ... }:
with lib;
with lib.cogisys;

let
  cfg = config.cogisys.apps.mpv;
  gui = config.cogisys.system.gui;
in
{
  options.cogisys.apps.mpv = with types; {
    enable = mkBoolOpt false "Enable mpv (with heavy configuration & plugins).";
  };

  config = mkIf cfg.enable {
    assertions = [(mkAssertionModule gui "GUI" "MPV")];

    environment.systemPackages = with pkgs; [
      (mpv.override {
        scripts = with pkgs.mpvScripts; [uosc thumbfast];
      })
    ];

    environment.

    environment.etc."mpv/mpv.conf".text = ''
      # AUTOGENERATED FILE - DO NOT EDIT!
      autofit-larger=100%x100%
      hwdec
      osd-bar=no
    '';
    
  };
}
